export const FilterOptions = {
  designation: [
    "Psychologist",
    "Astrologer",
    "MERN Developer",
    "Illustrator",
    "Digital Marketing",
    "Sale Consultant",
    "Graphic Designer",
    "Video Editor",
    "Social Media Manager",
  ],
  priority: ["Low", "Medium", "High", "Urgent"],
  department: [
    "Human Resources",
    "Design",
    "Development",
    "Sales",
    "Marketing",
    "Content Creation",
    "Customer Support",
    "Finance",
    "Operations",
    "Astrology",
    "Psychology",
  ],
  status: [
    "Pending",
    "In Progress",
    "Completed",
    "Overdue",
    "Completed Late",
    "Removed",
    "Extension Requested",
  ],
  jobType: ["Full Time", "Freelance", "Intern"],
};
