import { QuizCategory, QuizQuestion } from "../../types/redux/mythosQuizType";

export const MYTHOLOGYQUIZ: Record<QuizCategory, QuizQuestion[]> = {
  ramayan: [
    {
      id: 1,
      question: "Who wrote the Ramayana?",
      options: ["Tulsidas", "Vyasa", "Kalidasa", "Valmiki"],
      answer: "Valmiki",
    },
    {
      id: 2,
      question: "When was the Ramayana written?",
      options: [
        "100 years ago",
        "Around 500 BCE",
        "In 2020",
        "During Mughal period",
      ],
      answer: "Around 500 BCE",
    },
    {
      id: 3,
      question: "In which language was the Ramayana originally written?",
      options: ["Hindi", "Tamil", "Sanskrit", "English"],
      answer: "Sanskrit",
    },
    {
      id: 4,
      question: "How many verses (shlokas) are in the Ramayana?",
      options: ["10,000", "24,000", "50,000", "1,000"],
      answer: "24,000",
    },
    {
      id: 5,
      question: "Into how many parts (Kandas) is the Ramayana divided?",
      options: ["5", "6", "7", "10"],
      answer: "7",
    },
    {
      id: 6,
      question: "What does Ramayana teach us?",
      options: [
        "To follow Dharma",
        "To be rich",
        "To be powerful",
        "To win wars",
      ],
      answer: "To follow Dharma",
    },
    {
      id: 7,
      question: "Where does the story of Ramayana begin?",
      options: ["Lanka", "Ayodhya", "Mathura", "Dwarka"],
      answer: "Ayodhya",
    },
    {
      id: 8,
      question: "Where was Ravana’s kingdom located?",
      options: ["Ayodhya", "Hastinapur", "Lanka", "Indraprastha"],
      answer: "Lanka",
    },
    {
      id: 9,
      question: "How was the Ramayana first created?",
      options: [
        "As a movie",
        "As a poem (shlokas)",
        "As a song album",
        "As a painting",
      ],
      answer: "As a poem (shlokas)",
    },
    {
      id: 10,
      question: "Who is the hero of the Ramayana?",
      options: ["Krishna", "Rama", "Arjuna", "Shiva"],
      answer: "Rama",
    },
    {
      id: 11,
      question: "Who is Rama’s wife?",
      options: ["Draupadi", "Radha", "Sita", "Lakshmi"],
      answer: "Sita",
    },
    {
      id: 12,
      question: "Why did Rama go to the forest?",
      options: [
        "Because he was exiled",
        "For fun",
        "To fight demons",
        "To find treasure",
      ],
      answer: "Because he was exiled",
    },
    {
      id: 13,
      question: "How many years was Rama in exile?",
      options: ["7", "10", "14", "20"],
      answer: "14",
    },
    {
      id: 14,
      question: "Who kidnapped Sita?",
      options: ["Kansa", "Ravana", "Bali", "Duryodhana"],
      answer: "Ravana",
    },
    {
      id: 15,
      question: "Who helped Rama search for Sita?",
      options: ["Hanuman", "Indra", "Narada", "Ganesha"],
      answer: "Hanuman",
    },
    {
      id: 16,
      question: "Who built the bridge to Lanka?",
      options: ["Rama", "Lakshmana", "Nala", "Sugriva"],
      answer: "Nala",
    },
    {
      id: 17,
      question: "Who is Rama’s loyal brother?",
      options: ["Lakshmana", "Bharata", "Shatrughna", "Karna"],
      answer: "Lakshmana",
    },
    {
      id: 18,
      question: "What festival celebrates Rama’s return to Ayodhya?",
      options: ["Diwali", "Holi", "Navratri", "Pongal"],
      answer: "Diwali",
    },
  ],
  mahabharat: [
    {
      id: 1,
      question: "Who wrote the Mahabharata?",
      options: ["Valmiki", "Vyasa", "Kalidasa", "Tulsidas"],
      answer: "Vyasa",
    },
    {
      id: 2,
      question: "Which language was the Mahabharata originally written in?",
      options: ["Hindi", "Sanskrit", "Tamil", "English"],
      answer: "Sanskrit",
    },
    {
      id: 3,
      question: "Who are the five Pandavas?",
      options: [
        "Rama, Lakshmana, Bharat, Shatrughna, Hanuman",
        "Yudhishthira, Bhima, Arjuna, Nakula, Sahadeva",
        "Krishna, Balarama, Arjuna, Karna, Bhima",
        "Duryodhana, Dushasana, Karna, Shakuni, Ashwatthama",
      ],
      answer: "Yudhishthira, Bhima, Arjuna, Nakula, Sahadeva",
    },
    {
      id: 4,
      question: "Who is the eldest of the Pandavas?",
      options: ["Bhima", "Arjuna", "Yudhishthira", "Nakula"],
      answer: "Yudhishthira",
    },
    {
      id: 5,
      question: "Who was the main villain among the Kauravas?",
      options: ["Karna", "Shakuni", "Duryodhana", "Dushasana"],
      answer: "Duryodhana",
    },
    {
      id: 6,
      question: "How many Kauravas were there?",
      options: ["50", "100", "101", "108"],
      answer: "100",
    },
    {
      id: 7,
      question: "Who was Arjuna’s charioteer in the war?",
      options: ["Bhishma", "Krishna", "Karna", "Drona"],
      answer: "Krishna",
    },
    {
      id: 8,
      question: "What is the name of the battlefield of Mahabharata?",
      options: ["Ayodhya", "Kurukshetra", "Lanka", "Mathura"],
      answer: "Kurukshetra",
    },
    {
      id: 9,
      question: "What sacred text is part of the Mahabharata?",
      options: ["Ramcharitmanas", "Vedas", "Bhagavad Gita", "Upanishads"],
      answer: "Bhagavad Gita",
    },
    {
      id: 10,
      question: "Who taught the Bhagavad Gita?",
      options: ["Vyasa", "Krishna", "Arjuna", "Drona"],
      answer: "Krishna",
    },
    {
      id: 11,
      question: "Who was the teacher of both Pandavas and Kauravas?",
      options: ["Kripacharya", "Drona", "Bhishma", "Vidura"],
      answer: "Drona",
    },
    {
      id: 12,
      question: "Who killed Drona?",
      options: ["Arjuna", "Bhima", "Dhrishtadyumna", "Karna"],
      answer: "Dhrishtadyumna",
    },
    {
      id: 13,
      question: "Who killed Bhishma?",
      options: ["Arjuna", "Bhima", "Karna", "Krishna"],
      answer: "Arjuna",
    },
    {
      id: 14,
      question: "Who was Karna’s mother?",
      options: ["Kunti", "Gandhari", "Draupadi", "Subhadra"],
      answer: "Kunti",
    },
    {
      id: 15,
      question: "Who was Draupadi married to?",
      options: ["Only Arjuna", "All five Pandavas", "Bhima only", "Krishna"],
      answer: "All five Pandavas",
    },
    {
      id: 16,
      question: "How many days did the Kurukshetra war last?",
      options: ["10", "14", "18", "21"],
      answer: "18",
    },
    {
      id: 17,
      question: "Who killed Duryodhana?",
      options: ["Arjuna", "Bhima", "Krishna", "Sahadeva"],
      answer: "Bhima",
    },
    {
      id: 18,
      question: "What does Mahabharata teach us?",
      options: [
        "Only warfare",
        "Dharma and righteousness",
        "Wealth accumulation",
        "Politics only",
      ],
      answer: "Dharma and righteousness",
    },
  ],
  quran: [
    {
      id: 1,
      question: "What is the holy book of Islam?",
      options: ["Bible", "Quran", "Torah", "Vedas"],
      answer: "Quran",
    },
    {
      id: 2,
      question: "In which language was the Quran revealed?",
      options: ["Arabic", "English", "Hebrew", "Latin"],
      answer: "Arabic",
    },
    {
      id: 3,
      question: "Who received the revelations of the Quran?",
      options: ["Moses", "Jesus", "Muhammad", "Abraham"],
      answer: "Muhammad",
    },
    {
      id: 4,
      question: "Through whom were the revelations sent?",
      options: [
        "Angel Jibreel",
        "Angel Mikaeel",
        "Angel Israfeel",
        "Angel Azrael",
      ],
      answer: "Angel Jibreel",
    },
    {
      id: 5,
      question: "What is the first chapter of the Quran?",
      options: ["Al-Baqarah", "Al-Fatiha", "Al-Ikhlas", "An-Nas"],
      answer: "Al-Fatiha",
    },
    {
      id: 6,
      question: "How many chapters (Surahs) are in the Quran?",
      options: ["100", "114", "99", "120"],
      answer: "114",
    },
    {
      id: 7,
      question: "What is the longest Surah in the Quran?",
      options: ["Al-Fatiha", "Al-Baqarah", "Yaseen", "Al-Kahf"],
      answer: "Al-Baqarah",
    },
    {
      id: 8,
      question: "What is the shortest Surah in the Quran?",
      options: ["Al-Ikhlas", "Al-Kawthar", "An-Nas", "Al-Falaq"],
      answer: "Al-Kawthar",
    },
    {
      id: 9,
      question: "In which month was the Quran first revealed?",
      options: ["Ramadan", "Shawwal", "Muharram", "Rajab"],
      answer: "Ramadan",
    },
    {
      id: 10,
      question: "What is Laylat al-Qadr?",
      options: [
        "Night of Power",
        "Night of Travel",
        "Night of Prayer",
        "Night of Fasting",
      ],
      answer: "Night of Power",
    },
    {
      id: 11,
      question: "Where was Prophet Muhammad born?",
      options: ["Medina", "Mecca", "Jerusalem", "Cairo"],
      answer: "Mecca",
    },
    {
      id: 12,
      question: "What is the holy city of Islam?",
      options: ["Medina", "Mecca", "Jerusalem", "Baghdad"],
      answer: "Mecca",
    },
    {
      id: 13,
      question: "What is the direction Muslims face during prayer?",
      options: ["East", "West", "Kaaba", "North"],
      answer: "Kaaba",
    },
    {
      id: 14,
      question: "What is the Islamic declaration of faith called?",
      options: ["Salat", "Zakat", "Shahada", "Hajj"],
      answer: "Shahada",
    },
    {
      id: 15,
      question: "How many daily prayers are there in Islam?",
      options: ["3", "4", "5", "6"],
      answer: "5",
    },
    {
      id: 16,
      question: "What is fasting during Ramadan called?",
      options: ["Hajj", "Sawm", "Zakat", "Salat"],
      answer: "Sawm",
    },
    {
      id: 17,
      question: "What charity is given in Islam?",
      options: ["Sadaqah", "Zakat", "Fitrah", "All of these"],
      answer: "All of these",
    },
    {
      id: 18,
      question: "What is the pilgrimage to Mecca called?",
      options: ["Umrah", "Hajj", "Ziyarat", "Safar"],
      answer: "Hajj",
    },
    {
      id: 19,
      question: "Which Surah is known as the 'Heart of the Quran'?",
      options: ["Al-Fatiha", "Yaseen", "Al-Baqarah", "Al-Ikhlas"],
      answer: "Yaseen",
    },
    {
      id: 20,
      question: "How is the Quran divided?",
      options: ["Juz", "Verses", "Surahs", "All of these"],
      answer: "All of these",
    },
    {
      id: 21,
      question: "What does the Quran mainly teach?",
      options: [
        "Wealth and power",
        "Dharma only",
        "Faith, guidance, and righteousness",
        "War strategies",
      ],
      answer: "Faith, guidance, and righteousness",
    },
  ],
  bible: [
    {
      id: 1,
      question: "What is the holy book of Christianity?",
      options: ["Quran", "Bible", "Torah", "Vedas"],
      answer: "Bible",
    },
    {
      id: 2,
      question: "The Bible is divided into how many main parts?",
      options: ["1", "2", "3", "4"],
      answer: "2",
    },
    {
      id: 3,
      question: "What are the two parts of the Bible?",
      options: [
        "Old and New Testament",
        "First and Second Book",
        "Law and Gospel",
        "Torah and Psalms",
      ],
      answer: "Old and New Testament",
    },
    {
      id: 4,
      question: "Who is the central figure of the New Testament?",
      options: ["Moses", "Jesus", "Abraham", "David"],
      answer: "Jesus",
    },
    {
      id: 5,
      question: "Where was Jesus born?",
      options: ["Nazareth", "Bethlehem", "Jerusalem", "Rome"],
      answer: "Bethlehem",
    },
    {
      id: 6,
      question: "Who was the mother of Jesus?",
      options: ["Mary", "Martha", "Sarah", "Rebekah"],
      answer: "Mary",
    },
    {
      id: 7,
      question: "Who baptized Jesus?",
      options: ["Peter", "John the Baptist", "Paul", "Moses"],
      answer: "John the Baptist",
    },
    {
      id: 8,
      question: "How many disciples did Jesus have?",
      options: ["10", "11", "12", "13"],
      answer: "12",
    },
    {
      id: 9,
      question: "What is the first book of the Bible?",
      options: ["Exodus", "Genesis", "Psalms", "Matthew"],
      answer: "Genesis",
    },
    {
      id: 10,
      question: "Who built the ark?",
      options: ["Moses", "Noah", "Abraham", "David"],
      answer: "Noah",
    },
    {
      id: 11,
      question: "Who led the Israelites out of Egypt?",
      options: ["David", "Moses", "Joseph", "Solomon"],
      answer: "Moses",
    },
    {
      id: 12,
      question: "What is the last book of the Bible?",
      options: ["Revelation", "John", "Acts", "Luke"],
      answer: "Revelation",
    },
    {
      id: 13,
      question: "Who was known as the strongest man?",
      options: ["David", "Samson", "Solomon", "Peter"],
      answer: "Samson",
    },
    {
      id: 14,
      question: "Who killed Goliath?",
      options: ["Saul", "David", "Samuel", "Joshua"],
      answer: "David",
    },
    {
      id: 15,
      question: "What miracle did Jesus perform on water?",
      options: [
        "Turned it into fire",
        "Walked on water",
        "Made it disappear",
        "Turned it into sand",
      ],
      answer: "Walked on water",
    },
    {
      id: 16,
      question: "What is the holy day for Christians?",
      options: ["Friday", "Saturday", "Sunday", "Monday"],
      answer: "Sunday",
    },
    {
      id: 17,
      question: "What does the Bible mainly teach?",
      options: [
        "War strategies",
        "Love, faith, and forgiveness",
        "Politics",
        "Science only",
      ],
      answer: "Love, faith, and forgiveness",
    },
    {
      id: 18,
      question: "Who betrayed Jesus?",
      options: ["Peter", "Judas Iscariot", "John", "Paul"],
      answer: "Judas Iscariot",
    },
    {
      id: 19,
      question: "Where was Jesus crucified?",
      options: ["Rome", "Jerusalem", "Nazareth", "Bethlehem"],
      answer: "Jerusalem",
    },
    {
      id: 20,
      question: "What event celebrates Jesus' resurrection?",
      options: ["Christmas", "Easter", "Good Friday", "Pentecost"],
      answer: "Easter",
    },
    {
      id: 21,
      question: "What is the place of worship for Christians?",
      options: ["Mosque", "Temple", "Church", "Synagogue"],
      answer: "Church",
    },
  ],
};
