import { BLOGS, MYTHOS_NEWS, NEWS } from "./blogs";
import { CONTACT_INFO, CAREER, PLANET } from "./footer";
import { MYTHOS_PLANS } from "./membershipPlans";
import { PROBLEMS_FACED } from "./problemsFaced";
import { SUNSHINE } from "./sunshine";
import { MYTHOS_FAQ } from "./faq";
import { MYTHOS_PODCASTS } from "./podcasts";
import {
  PSYCHOLOGISTS_REQUIREMENTS,
  ASTROLOGER_INTERN_REQUIREMENT,
  ASTROLOGER_REQUIREMENTS,
  PSYCHOLOGIST_INTERN_REQUIREMENTS,
} from "./hiring";
import { ZODIAC_NAME_MAPPING, ZODIAC_DATA, RASHI_DETAILS } from "./zodiac";
import { COUNTRY_NAMES } from "./profile";

export {
  BLOGS,
  MYTHOS_NEWS,
  NEWS,
  CONTACT_INFO,
  CAREER,
  PLANET,
  MYTHOS_PLANS,
  PROBLEMS_FACED,
  SUNSHINE,
  MYTHOS_FAQ,
  MYTHOS_PODCASTS,
  ZODIAC_DATA,
  PSYCHOLOGISTS_REQUIREMENTS,
  ASTROLOGER_INTERN_REQUIREMENT,
  ASTROLOGER_REQUIREMENTS,
  PSYCHOLOGIST_INTERN_REQUIREMENTS,
  ZODIAC_NAME_MAPPING,
  RASHI_DETAILS,
  COUNTRY_NAMES,
};
